coverage:
  status:
    project:
      default:
        # basic
        target: auto #default
        threshold: 5
        base: auto
        flags:
          - unit
        paths:
          - "src"
       # advanced settings
        branches:
          - master
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false
    patch:
      default:
        # basic
        target: auto
        threshold: 10%
        base: auto
        # advanced
        branches:
          - master
        if_ci_failed: failure #success, failure, error, ignore
        only_pulls: true
        flags:
          - "unit"
        paths:
          - "src"

ignore:
  - ".github"  # ignore folders and all its contents
  - ".vscode"  # ignore folders and all its contents
  - "README.md"  # ignore folders and all its contents
  - "LICENSE"  # ignore folders and all its contents
  - "tsconfig.json"  # ignore folders and all its contents

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
